[features]
seeds = false
skip-lint = false
[programs.localnet]
garden = "55KrogTBFDAg2XvdbgdzqoPRJWga89QQwD4nj7qBBpKC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "../keys/localkey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
